name: CI

on: [push]

env:
  HUSKY: 0

jobs:
  build:
    if: github.repository == 'seemorg/markdown-parser' && (github.ref == 'refs/heads/main') && github.event_name != 'pull_request'
    name: ⚒️ Build, lint, and test

    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint --quiet

      - name: Test
        run: yarn test:coverage

      - name: Build
        run: yarn build

  test-and-publish:
    name: 🎉 Publish to NPM
    needs: [build]
    if: github.repository == 'seemorg/markdown-parser' && (github.ref == 'refs/heads/main') && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - run: npx semantic-release@17
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
