name: PR

on: [pull_request]

env:
  HUSKY: 0

jobs:
  build:
    name: ⚒️ Build, lint, and test

    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint --quiet

      - name: Test
        run: yarn test:coverage

      - name: Build
        run: yarn build

  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Analyze bundle size
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
